// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "7be96e84-f2e8-4346-9d04-dbe35051fe47";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onSetTextCChange();

String debugMessengeC;
String setTextC;
float VentTimeC;
int onTimeC;
int TempS1C;
int TempS2C;
int TempS3C;
int TextC;
bool onC;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(debugMessengeC, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(setTextC, READWRITE, ON_CHANGE, onSetTextCChange);
  ArduinoCloud.addProperty(VentTimeC, READ, 1800 * SECONDS, NULL);
  ArduinoCloud.addProperty(onTimeC, READ, 7200 * SECONDS, NULL);
  ArduinoCloud.addProperty(TempS1C, READ, 1800 * SECONDS, NULL);
  ArduinoCloud.addProperty(TempS2C, READ, 1800 * SECONDS, NULL);
  ArduinoCloud.addProperty(TempS3C, READ, 1800 * SECONDS, NULL);
  ArduinoCloud.addProperty(TextC, READ, 1800 * SECONDS, NULL);
  ArduinoCloud.addProperty(onC, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
